# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Angular 2 UI
email: krzysztof.bogdan@codeweaver.pl
description: > # this means to ignore newlines until "baseurl:"
  Bundle of easy to use Angular 2 components.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://a2ui.com" # the base hostname & protocol for your site
github_username:  Krzysztof Bogdan
repository: rzysztofBogdan/a2ui-site
# Build settings
markdown: kramdown

collections:
  - mains
